### ISSUE TITLE
Use latest version of nsconfig

### ISSUE THREAD

**Issue by jacobsvante** [suiteplus/nscabinet#18]
First of all thanks for an awesome lib, it really increases my productivity when working with NetSuite.

Would be nice if you could keep the `nsconfig` version up to date in this lib. Would be nice to get the `passwordHash` functionality.

And while you're at it merging in https://github.com/suiteplus/nsconfig/pull/7 would help a lot also for working with multiple NS environments.

**Comment by jacobsvante** [comment]
I updated the `package.json` to use `nsconfig@0.5.0` just to test. With the new version I'm getting the following error when doing an upload:

``` js
Uploading myscript.js to /SuiteScripts
_http_outgoing.js:348
    throw new TypeError('The header content contains invalid characters');
    ^

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:196:15)
    at Request.start (/path/to/node_modules/request/request.js:747:30)
    at Request.write (/path/to/node_modules/request/request.js:1369:10)
    at end (/path/to/node_modules/request/request.js:561:16)
    at Immediate._onImmediate (/path/to/node_modules/request/request.js:589:7)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by wkrueger** [comment]
Hmm seems the npm version is outdated. Could you test a npm install from git while we update npm?

`npm i https://github.com/suiteplus/nscabinet.git`

Thanks!

**Comment by jacobsvante** [comment]
Ah, didn't realize you had updated the version in the repo, sorry for that! It works great with the current master. Perhaps we could see a `0.5.2` release? 😀
