### ISSUE TITLE
 Unexpected token <

### ISSUE THREAD

**Issue by dev-renovationbrands** [suiteplus/nscabinet#20]
Uploading foo.js to /SuiteScripts
C:\rb\git\rb-netsuite-template\node_modules\nscabinet\src\nscabinet.js:186
            throw Error('Unable to parse response: ' + e);
            ^

Error: Unable to parse response: SyntaxError: Unexpected token <
    at Error (native)
    at DestroyableTransform.flush [as _flush](C:rbgitrb-netsuite-templatenode_modulesnscabinetsrcnscabinet.js:186:19)
    at DestroyableTransform.<anonymous> (C:\rb\git\rb-netsuite-template\node_modules\through2\node_modules\readable-stream\lib_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (C:\rb\git\rb-netsuite-template\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:465:12)
    at finishMaybe (C:\rb\git\rb-netsuite-template\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:477:7)
    at endWritable (C:\rb\git\rb-netsuite-template\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (C:\rb\git\rb-netsuite-template\node_modules\through2\node_modules\readable-stream\lib_stream_writable.js:455:41)

**Comment by dev-renovationbrands** [comment]
Any ideas?

**Comment by wkrueger** [comment]
seems like netsuite sending back an HTML error page instead of json for some reason (when calling the restlet)... Not usual. Netsuite usually sends back proper responses for the most common error cases (i.e. wrong credentials, wrong script id, et cetera)

You'd have to end up debugging/adding debugging code to see whats netsuite's response (and it  is probably something unmeaningful like "page not found"). You may try also sending any request (even empty) to the restlet with something like postman to see what's the response...
